"""api catalog: apis, versions, quotas, rate_limit_rules

Revision ID: 3b0a3e40e787
Revises: 4d0d14f33a23
Create Date: 2026-08-10 01:38:48.101200
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3b0a3e40e787"
down_revision: str | None = "4d0d14f33a23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apis",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_apis_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apis")),
        sa.UniqueConstraint("organization_id", "slug", name="uq_apis_org_slug"),
    )
    op.create_index(op.f("ix_apis_organization_id"), "apis", ["organization_id"], unique=False)
    op.create_table(
        "api_versions",
        sa.Column("api_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("upstream_base_url", sa.String(length=2048), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_id"], ["apis.id"], name=op.f("fk_api_versions_api_id_apis"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_versions")),
        sa.UniqueConstraint("api_id", "version", name="uq_api_versions_api_version"),
    )
    op.create_index(op.f("ix_api_versions_api_id"), "api_versions", ["api_id"], unique=False)
    op.create_table(
        "quotas",
        sa.Column("api_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("max_requests", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_id"], ["apis.id"], name=op.f("fk_quotas_api_id_apis"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotas")),
        sa.UniqueConstraint("api_id", "period", name="uq_quotas_api_period"),
    )
    op.create_index(op.f("ix_quotas_api_id"), "quotas", ["api_id"], unique=False)
    op.create_table(
        "rate_limit_rules",
        sa.Column("api_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.String(length=24), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("burst", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_id"],
            ["apis.id"],
            name=op.f("fk_rate_limit_rules_api_id_apis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_rules")),
        sa.UniqueConstraint("api_id", name="uq_rate_limit_rules_api"),
    )
    op.create_index(
        op.f("ix_rate_limit_rules_api_id"), "rate_limit_rules", ["api_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_limit_rules_api_id"), table_name="rate_limit_rules")
    op.drop_table("rate_limit_rules")
    op.drop_index(op.f("ix_quotas_api_id"), table_name="quotas")
    op.drop_table("quotas")
    op.drop_index(op.f("ix_api_versions_api_id"), table_name="api_versions")
    op.drop_table("api_versions")
    op.drop_index(op.f("ix_apis_organization_id"), table_name="apis")
    op.drop_table("apis")
    # ### end Alembic commands ###
