"""analytics: daily_usage rollup

Revision ID: 5116f937ace7
Revises: 74a92ae4539c
Create Date: 2026-08-10 02:06:21.307967
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5116f937ace7"
down_revision: str | None = "74a92ae4539c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_usage",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("api_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("total_latency_ms", sa.Float(), nullable=False),
        sa.Column("total_request_bytes", sa.Integer(), nullable=False),
        sa.Column("total_response_bytes", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_usage")),
        sa.UniqueConstraint("api_id", "usage_date", name="uq_daily_usage_api_date"),
    )
    op.create_index(
        "ix_daily_usage_org_date", "daily_usage", ["organization_id", "usage_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_daily_usage_org_date", table_name="daily_usage")
    op.drop_table("daily_usage")
    # ### end Alembic commands ###
